---
- name: Install Firewalld
  package:
    name: firewalld

- name: Enable and start Firewalld
  service:
    name: firewalld
    state: started
    enabled: true

- name: Configure Firewalld services
  firewalld:
    service: "{{ ('/' in item) | ternary(omit, item) }}"
    port: "{{ ('/' in item) | ternary(item, omit) }}"
    state: enabled
    immediate: true
    permanent: true
  loop: "{{ fwd_services }}"
  notify: Firewall settings changed
